config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :customers
  resources :customers

  root :to => 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
    
   before_save do
        self.VegToppings.gsub!(/[\[\]\"]/,"") if attribute_present?("VegToppings")
        self.NonVegToppings.gsub!(/[\[\]\"]/,"") if attribute_present?("NonVegToppings")
        
   end

  canadian_postal_code = /\A[a-zA-Z]\d{1}[a-zA-Z](\-| |)\d{1}[a-zA-Z]\d{1}\z/
  validates :PostalCode, format: { with: canadian_postal_code }
  validates :Appartment, presence:true
  validates :Street, presence:true
  validates :City, presence:true
  validates :Size, presence:true
  validates :Crust, presence:true
  
  

  
      def Price
        @crust1 = 0
        @TotalPrice = 0
        
        @VegToppingsPrice = 0
        @NonVegToppingsPrice = 0
        @Tax = 0
      
        if self.Size == "Small"
          @TotalPrice = 5.00
        elsif self.Size == "Medium"
          @TotalPrice = 10.00
        elsif self.Size == "Large"
          @TotalPrice = 15.00
        elsif self.Size == "X-Large"
          @TotalPrice = 20.00
        end
        
         if attribute_present?("VegToppings")
         @VegToppingsPrice = self.VegToppings.count(',') * 0.5
         end
        
         if attribute_present?("NonVegToppings")
         @NonVegToppingsPrice = self.NonVegToppings.count(',') * 0.5
         end
        
        
        if self.Crust == "Stuffed Crust"
          @crust1 = 2.00
        end
        
        if self.Province == "Ontario"
           @Tax = 0.13
        elsif self.Province == "Manitoba"
           @Tax = 0.10
        elsif self.Province == "Saskatchewan"
           @Tax = 0.15
        elsif self.Province == "Quebec"
           @Tax = 0.11
        end
            @TotalPrice = @TotalPrice + @crust1 + @VegToppingsPrice + @NonVegToppingsPrice
            
               # return (@TotalPrice)
                return ((@Tax * @TotalPrice) + @TotalPrice)
        
      
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:NAME)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
   # orders_id = Order.find(params[:id])
  #  @orders_id = orders_id.select!{ |s| s.customer_id = current_customer.id } unless admin?
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:Appartment, :Street, :City, :PostalCode, :Province, :Size, :Crust, :Price, VegToppings:[] , NonVegToppings:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
     def checked(area)
        @order.VegToppings.nil? ? false : @order.VegToppings.match(area)
        @order.NonVegToppings.nil? ? false : @order.NonVegToppings.match(area)
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NAME %><br>
    <%= f.text_field :NAME %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
 <div class="container1">
				<div class="col-md-16">
                  <div class="panel panel-primary">
                    <div class="panel panel-heading">
                      <span class="glyphicon glyphicon-user"></span> Listing Customers
					  </div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.NAME %></td>
        <td><%= link_to 'Show', customer , :class=>'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) ,:class=>'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' },:class=>'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<div class="container1">
  <div class="col-md-16">
    <div class="panel panel-primary">
       <div class="panel panel-heading">
         <span class="glyphicon glyphicon-user"></span> New Customers
</div>



<%= render 'form' %>

<%= link_to 'Back', customers_path,:class=>"btn btn-danger" %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.NAME %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ="container">
			<div class="jumbotron">
			   <h3>WELCOME TO CONESTOGA PIZZERIA</h3>
				</div>
				    <div class ="container"></div>
				      	<nav class="navbar navbar-default">
                	<div class="navbar-header">
							    	<ul class="nav navbar-nav">
									<li class="active"><%= link_to 'Home', customers_path %></li>
										<li><%= link_to 'Orders', orders_path %></li>
										 
									    <% if customer_signed_in? %>
  									<% if current_customer.admin? %>
  									<li>
  									  <%= link_to 'Show All Orders', orders_path  %>   
  									 </li>
  									<% end %>
                    <li>
                    <%= link_to('Logout', destroy_customer_session_path, :method => :delete) %>        
                    </li>
                  <% else %>
                    <li>
                    <%= link_to('Login', new_customer_session_path)  %>  
                    </li>
                  <% end %>
								</ul>
							</div>       
				   </nav>
                    </div>
 <div class = "container" id="yield">
   
   
<%= yield %>
</div>
</body>
</html>
 

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Appartment %><br>
    <%= f.text_field :Appartment %>
  </div>
  <div class="field">
    <%= f.label :Street %><br>
    <%= f.text_field :Street %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :PostalCode %><br>
    <%= f.text_field :PostalCode %>
  </div>
  <div class="field">
    <%= f.label :Province %><br>
    <%= select("order", "Province", options_for_select([['Ontario', 'Ontario'], ['Manitoba', 'Manitoba'], ['Saskatchewan','Saskatchewan'],['Quebec','Quebec']])) %>
  
  </div>
  <div class="field">
    <%= f.radio_button("Size", "Small", :value => "Small") %>
    <%= label_tag(:Size, "Small") %>
    
    <%= f.radio_button("Size", "Medium", :value => "Medium") %>
    <%= label_tag(:Size, "Medium") %>
    
    <%= f.radio_button("Size", "Large", :value => "Large") %>
    <%= label_tag(:Size, "Large") %>
    
    <%= f.radio_button("Size", "X-Large", :value => "X-Large") %>
    <%= label_tag(:Size, "X-Large") %>
</div>

  <div class="field">
   <%= f.label :VEGTOPPINGS%><br>
    <%= label_tag 'vegtoppings_onions', 'Onions' %>
    <%= check_box_tag 'order[VegToppings][]', 'Onions', checked('Onions'), id: 'vegtoppings_onions' %>
    
    <%= label_tag 'vegtoppings_pineapple', 'Pineapple' %>
    <%= check_box_tag 'order[VegToppings][]', 'Pineapple', checked('Pineapple'), id: 'vegtoppings_pineapple' %>
    
    <%= label_tag 'vegtoppings_capsicum', 'Capsicum' %>
    <%= check_box_tag 'order[VegToppings][]', 'Capsicum', checked('Capsicum'), id: 'vegtoppings_capsicum ' %>
    
    <%= label_tag 'vegtoppings_mushroom', 'Mushroom' %>
    <%= check_box_tag 'order[VegToppings][]', 'Mushroom', checked('Mushroom'), id: 'vegtoppings_mushroom ' %>
    
    <%= label_tag 'vegtoppings_greenolives', 'GreenOlives' %>
    <%= check_box_tag 'order[VegToppings][]', 'GreenOlives', checked('GreenOlives'), id: 'vegtoppings_greenolives ' %>
    
    <%= label_tag 'vegtoppings_blackpeppers', 'BlackPeppers' %>
    <%= check_box_tag 'order[VegToppings][]', 'BlackPeppers', checked('BlackPeppers'), id: 'vegtoppings_blackpeppers ' %>
   </div>
   
  <div class="field">
      <%= f.label :NONVEGTOPPINGS%><br>
    <%= label_tag 'nonvegtoppings_pepproni', 'Pepproni' %>
    <%= check_box_tag 'order[NonVegToppings][]', 'Pepproni', checked('Pepproni'), id: 'nonvegtoppings_pepproni' %>
    
    <%= label_tag 'nonvegtoppings_sausage', 'Sausage' %>
    <%= check_box_tag 'order[NonVegToppings][]', 'Sausage', checked('Sausage'), id: 'nonvegtoppings_sausage' %>
    
    <%= label_tag 'nonvegtoppings_beaf', 'Beaf' %>
    <%= check_box_tag 'order[NonVegToppings][]', 'Beaf', checked('Beaf'), id: 'nonvegtoppings_beaf ' %>
    
    <%= label_tag 'nonvegtoppings_ham', 'Ham' %>
    <%= check_box_tag 'order[NonVegToppings][]', 'Ham', checked('Ham'), id: 'nonvegtoppings_ham' %>
    
    <%= label_tag 'nonvegtoppings_bacon', 'Bacon' %>
    <%= check_box_tag 'order[NonVegToppings][]', 'Bacon', checked('Bacon'), id: 'nonvegtoppings_bacon ' %>
    
 </div>
 
  <div class="field">
    <%= f.label :Crust %><br>
    <%= f.radio_button("Crust", "Original Hand Tossed") %>
    <%= label_tag(:crust, "Original Hand Tossed") %>
    
    <%= f.radio_button("Crust", "Stuffed Crust") %>
    <%= label_tag(:crust, "Stuffed Crust") %>
    
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  
  
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
 <div class="container1">
				<div class="col-md-16">
                  <div class="panel panel-primary">
                    <div class="panel panel-heading">
                      <span class="glyphicon glyphicon-search"></span> Listing Orders
					  </div>


<table>
  <thead>
    <tr>
      <th>Appartment</th>
      <th>Street</th>
      <th>City</th>
      <th>Postalcode</th>
      <th>Province</th>
      <th>Size</th>
      <th>Vegtoppings</th>
      <th>Nonvegtoppings</th>
      <th>Crust</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.Appartment %></td>
          <td><%= order.Street %></td>
          <td><%= order.City %></td>
          <td><%= order.PostalCode %></td>
          <td><%= order.Province %></td>
          <td><%= order.Size %></td>
          <td><%= order.VegToppings %></td>
          <td><%= order.NonVegToppings %></td>
          <td><%= order.Crust %></td>
          <td><%= order.Price %></td>
          
          
        
          <td><%= link_to 'Show', order ,:class =>'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_order_path(order) ,:class =>'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'btn btn-primary' %></td>
        </tr>
      <% end %>
    
    
    
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path ,:class =>'btn btn-primary'%>

app/views/orders/new.html.erb
<div id="wrapper">
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back',  orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appartment:</strong>
  <%= @order.Appartment %>
</p>

<p>
  <strong>Street:</strong>
  <%= @order.Street %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.City %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @order.PostalCode %>
</p>

<p>
  <strong>Province:</strong>
  <%= @order.Province %>
</p>

<p>
  <strong>Size:</strong>
  <%= @order.Size %>
</p>

<p>
  <strong>Vegtoppings:</strong>
  <%= @order.VegToppings %>
</p>

<p>
  <strong>Nonvegtoppings:</strong>
  <%= @order.NonVegToppings %>
</p>

<p>
  <strong>Crust:</strong>
  <%= @order.Crust %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.Price %> 
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>